const catalogue = [
  { id: "pastel-poisson-fume", family: "pastel", name: "Pastel Poisson fumé", description: "Poisson fumé, légumes.", price: 250, unitLabel: "pièce", imagePath: "/assets/refonte/pastels-generous.jpg", portion: "Pastel généreux", announcedQuantity: null, isEstimatedPrice: false, isActive: true, position: 1 },
  { id: "pastel-classique", family: "pastel", name: "Pastel Classique", description: "Sardines.", price: 300, unitLabel: "pièce", imagePath: "/assets/pastels_et_crepes_jpeg/pastel-classique.jpg", portion: "Demi-lune généreuse", announcedQuantity: null, isEstimatedPrice: false, isActive: true, position: 2 },
  { id: "pastel-gourmand", family: "pastel", name: "Pastel Gourmand", description: "Garniture au choix : sardine, saucisse ou œuf.", price: 350, unitLabel: "pièce", imagePath: "/assets/pastels_et_crepes_jpeg/pastel-gourmand.jpg", portion: "Plus de garniture", announcedQuantity: null, isEstimatedPrice: true, isActive: true, position: 3 },
  { id: "crepe-chocolat", family: "crepe", name: "Crêpe Chocolat", description: "Crêpe longue et moelleuse garnie de chocolat fondant.", price: 500, unitLabel: "pièce", imagePath: "/assets/pastels_et_crepes_jpeg/crepe-chocolat.jpg", portion: "Crêpe généreuse", announcedQuantity: null, isEstimatedPrice: false, isActive: true, position: 4 },
  { id: "crepe-vanille", family: "crepe", name: "Crêpe Vanille", description: "Crêpe longue et souple à la vanille.", price: 300, unitLabel: "pièce", imagePath: "/assets/refonte/crepes-generous.jpg", portion: "Crêpe généreuse", announcedQuantity: null, isEstimatedPrice: false, isActive: true, position: 5 },
  { id: "box-petite-vanille", family: "box", name: "Petite Box Vanille", description: "7 crêpes roulées à la vanille.", price: 1500, unitLabel: "box", imagePath: "/assets/offres/petite-box-vanille-7.jpg", portion: null, announcedQuantity: 7, isEstimatedPrice: false, isActive: true, position: 6 },
  { id: "box-petite-chocolat", family: "box", name: "Petite Box Chocolat", description: "6 crêpes roulées au chocolat.", price: 2500, unitLabel: "box", imagePath: "/assets/offres/petite-box-chocolat-6.jpg", portion: null, announcedQuantity: 6, isEstimatedPrice: false, isActive: true, position: 7 },
  { id: "box-petite-chocolat-banane", family: "box", name: "Petite Box Chocolat-Banane", description: "6 crêpes roulées au chocolat et à la banane.", price: 3500, unitLabel: "box", imagePath: "/assets/offres/petite-box-chocolat-banane-6.jpg", portion: null, announcedQuantity: 6, isEstimatedPrice: false, isActive: true, position: 8 },
  { id: "box-classique-vanille", family: "box", name: "Box Classique Vanille", description: "10 crêpes roulées à la vanille.", price: 2400, unitLabel: "box", imagePath: "/assets/offres/box-classique-vanille-10.jpg", portion: null, announcedQuantity: 10, isEstimatedPrice: false, isActive: true, position: 9 },
  { id: "box-classique-chocolat", family: "box", name: "Box Classique Chocolat", description: "9 crêpes roulées au chocolat.", price: 4000, unitLabel: "box", imagePath: "/assets/offres/box-classique-chocolat-9.jpg", portion: null, announcedQuantity: 9, isEstimatedPrice: false, isActive: true, position: 10 },
  { id: "box-classique-chocolat-banane", family: "box", name: "Box Classique Chocolat-Banane", description: "9 crêpes roulées au chocolat et à la banane.", price: 5600, unitLabel: "box", imagePath: "/assets/offres/box-classique-chocolat-banane-9.jpg", portion: null, announcedQuantity: 9, isEstimatedPrice: false, isActive: true, position: 11 },
  { id: "offer-5-poisson-fume", family: "pastel-offer", name: "5 Pastels Poisson fumé", description: "5 pastels au poisson fumé.", price: 1000, unitLabel: "formule", imagePath: "/assets/offres/formule-5-poisson-fume.jpg", portion: null, announcedQuantity: 5, isEstimatedPrice: false, isActive: true, position: 12 },
  { id: "offer-5-classique", family: "pastel-offer", name: "5 Pastels Classique", description: "5 pastels classiques à la sardine.", price: 1200, unitLabel: "formule", imagePath: "/assets/offres/formule-5-classique.jpg", portion: null, announcedQuantity: 5, isEstimatedPrice: false, isActive: true, position: 13 },
  { id: "offer-5-gourmand", family: "pastel-offer", name: "5 Pastels Gourmand", description: "5 pastels gourmands.", price: 1500, unitLabel: "formule", imagePath: "/assets/offres/formule-5-gourmand.jpg", portion: null, announcedQuantity: 5, isEstimatedPrice: false, isActive: true, position: 14 },
  { id: "offer-11-poisson-fume", family: "pastel-offer", name: "11 Pastels Poisson fumé", description: "11 pastels au poisson fumé.", price: 2000, unitLabel: "formule", imagePath: "/assets/offres/formule-11-poisson-fume.jpg", portion: null, announcedQuantity: 11, isEstimatedPrice: false, isActive: true, position: 15 },
  { id: "offer-11-classique", family: "pastel-offer", name: "11 Pastels Classique", description: "11 pastels classiques à la sardine.", price: 2400, unitLabel: "formule", imagePath: "/assets/offres/formule-11-classique.jpg", portion: null, announcedQuantity: 11, isEstimatedPrice: false, isActive: true, position: 16 },
  { id: "offer-11-gourmand", family: "pastel-offer", name: "11 Pastels Gourmand", description: "11 pastels gourmands.", price: 3000, unitLabel: "formule", imagePath: "/assets/offres/formule-11-gourmand.jpg", portion: null, announcedQuantity: 11, isEstimatedPrice: false, isActive: true, position: 17 }
];

module.exports = { catalogue };
